name: gyroscope
description: A Flutter plugin to use Gyroscope in flutter using Android and IOS native.
version: 0.0.1
homepage: https://github.com/sikandernoori/gyroscope

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hunaindev.gyroscope
        pluginClass: GyroscopePlugin
      ios:
        pluginClass: GyroscopePlugin
